
--DISTRICT is equivalent to DISTRITO
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (1, 'Aveiro');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (2, 'Beja');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (3, 'Braga');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (4, 'Bragança');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (5, 'Castelo Branco');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (6, 'Coimbra');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (7, 'Évora');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (8, 'Faro');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (9, 'Guarda');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (10, 'Leiria');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (11, 'Lisboa');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (12, 'Portalegre');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (13, 'Porto');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (14, 'Santarém');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (15, 'Setúbal');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (16, 'Viana do Castelo');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (17, 'Vila Real');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (18, 'Viseu');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (19, 'Ilha da Madeira');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (20, 'Ilha de Porto Santo');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (21, 'Ilha de Santa Maria');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (22, 'Ilha de São Miguel');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (23, 'Ilha Terceira');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (24, 'Ilha da Graciosa');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (25, 'Ilha de São Jorge');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (26, 'Ilha do Pico');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (27, 'Ilha do Faial');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (28, 'Ilha das Flores');
INSERT INTO DISTRICT(DISTRICT_ID, DISTRICT_NAME) VALUES (29, 'Ilha do Corvo');

--REGION is equivalent to CONCELHO
--PORTO
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (1, 'Amarante', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (2, 'Baião', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (3, 'Felgueiras', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (4, 'Gondomar', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (5, 'Lousada', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (6, 'Maia', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (7, 'Marco de Canavezes', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (8, 'Matosinhos', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (9, 'Paços de Ferreira', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (10, 'Paredes', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (11, 'Penafiel', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (12, 'Porto', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (13, 'Santo Tirso', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (14, 'Trofa', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (15, 'Valongo', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (16, 'Vila do Conde', 13);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (17, 'Vila Nova de Gaia', 13);
--Aveiro
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (18, 'Águeda', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (19, 'Albergaria-a-Velha', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (20, 'Anadia', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (21, 'Arouca', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (22, 'Aveiro', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (23, 'Castelo de Paiva', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (24, 'Espinho', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (25, 'Estarreja', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (26, 'Ílhavo', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (27, 'Mealhada', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (28, 'Murtosa', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (29, 'Oliveira de Azeméis', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (30, 'Oliveira do Bairro', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (31, 'Ovar', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (32, 'Santa Maria da Feira', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (33, 'São João da Madeira', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (34, 'Sever do Vouga', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (35, 'Vagos', 1);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (36, 'Vale de Cambra', 1);
--Beja
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (37, 'Aljustrel', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (38, 'Almodôvar', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (39, 'Alvito', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (40, 'Barrancos', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (41, 'Beja', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (42, 'Castro Verde', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (43, 'Cuba', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (44, 'Ferreira do Aletejo', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (45, 'Mértola', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (46, 'Moura', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (47, 'Odemira', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (48, 'Ourique', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (49, 'Serpa', 2);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (50, 'Vidigueira', 2);
--Braga
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (51, 'Amares', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (52, 'Barcelos', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (53, 'Braga', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (54, 'Cabeceiras de Basto', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (55, 'Celourico de Basto', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (56, 'Esposende', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (57, 'Fafe', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (58, 'Guimarães', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (59, 'Póvoa de Lanhoso', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (60, 'Terras de Bouro', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (61, 'Vieira do Minho', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (62, 'Vila Nova de Famalicão', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (63, 'Vila Verde', 3);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (64, 'Vizela', 3);
--Bragança
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (65, 'Alfandega da Fé', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (66, 'Bragança', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (67, 'Carrazeda de Ansiães', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (68, 'Freixo de Espada à Cinta', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (69, 'Macedo de Cavaleiros', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (70, 'Miranda do Douro', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (71, 'Mirandela', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (72, 'Mogadouro', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (73, 'Torre de Moncorvo', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (74, 'Vila Flor', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (75, 'Vimioso', 4);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (76, 'Vinhais', 4);
--Castelo Branco
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (77, 'Belmonte', 5);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (78, 'Castelo Branco', 5);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (79, 'Covilhã', 5);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (80, 'Fundão', 5);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (81, 'Idanha-a-Nova', 5);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (82, 'Oleiros', 5);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (83, 'Penamacor', 5);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (84, 'Proença-a-Nova', 5);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (85, 'Sertã', 5);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (86, 'Vila de Rei', 5);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (87, 'Vila Velha de Ródão', 5);
--Coimbra
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (88, 'Arganil', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (89, 'Cantanhede', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (90, 'Coimbra', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (91, 'Condeixa-a-Nova', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (92, 'Figueira da Foz', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (93, 'Góis', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (94, 'Lousã', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (95, 'Mira', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (96, 'Miranda do Corvo', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (97, 'Montemor-o-Velho', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (98, 'Oliveira do hospital', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (99, 'Pampilhosa da Serra', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (100, 'Penacova', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (101, 'Penela', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (102, 'Soure', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (103, 'Tábua', 6);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (104, 'Vila Nova de Poiares', 6);
--Évora
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (105, 'Alandroal', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (106, 'Arraiolos', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (107, 'Borba', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (108, 'Estremoz', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (109, 'Évora', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (110, 'Montemor-o-Novo', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (111, 'Mora', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (112, 'Mourão', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (113, 'Portel', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (114, 'Redondo', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (115, 'Reguengos de Monsaraz', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (116, 'Vendas Novas', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (117, 'Viana do Alentejo', 7);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (118, 'Vila Viçosa', 7);
--Faro
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (119, 'Albufeira', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (120, 'Alcoutim', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (121, 'Aljezur', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (122, 'Castro Marim', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (123, 'Faro', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (124, 'Lagoa', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (125, 'Lagos', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (126, 'Loulé', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (127, 'Monchique', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (128, 'Olhão', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (129, 'Portimão', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (130, 'São Brás de Alportel', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (131, 'Silves', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (132, 'Tavira', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (133, 'Vila do Bispo', 8);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (134, 'Vila Real de Santo António', 8);
--Guarda
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (135, 'Aguiar da Beira', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (136, 'Almeida', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (137, 'Celourico da Beira', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (138, 'Figueira de Castelo Rodrigo', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (139, 'Fornos de Algodres', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (140, 'Gouveia', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (141, 'Guarda', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (142, 'Manteigas', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (143, 'Mêda', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (144, 'Pinhel', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (145, 'Sabugal', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (146, 'Seia', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (147, 'Trancoso', 9);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (148, 'Vila Nova de Foz Côa', 9);
--Leiria
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (149, 'Alcobaça', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (150, 'Alvaiázere', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (151, 'Ansião', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (152, 'Batalha', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (153, 'Bombarral', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (154, 'Caldas da Rainha', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (155, 'Castanheira de Pera', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (156, 'Figueiró dos Vinhos', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (157, 'Leiria', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (158, 'Marinha Grande', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (159, 'Nazaré', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (160, 'Óbidos', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (161, 'Pedrógão Grande', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (162, 'Peniche', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (163, 'Pombal', 10);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (164, 'Porto de Mós', 10);
--Lisboa
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (165, 'Alenquer', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (166, 'Amadora', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (167, 'Arruda dos Vinhos', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (168, 'Azambuja', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (169, 'Cadaval', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (170, 'Cascais', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (171, 'Lisboa', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (172, 'Loures', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (173, 'Lourinhã', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (174, 'Mafra', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (175, 'Odivelas', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (176, 'Oeiras', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (177, 'Sintra', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (178, 'Sobral de Monte Agraço', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (179, 'Torres Vedras', 11);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (180, 'Vila Franca de Xira', 11);
--Portalegre
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (181, 'Alter do Chão', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (182, 'Arronches', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (183, 'Avis', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (184, 'Campo Maior', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (185, 'Castelo de Vide', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (186, 'Crato', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (187, 'Elvas', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (188, 'Fronteira', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (189, 'Gavião', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (190, 'Marvão', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (191, 'Monforte', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (192, 'Nisa', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (193, 'Ponte de Sôr', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (194, 'Portalegre', 12);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (195, 'Sousel', 12);
--Santarém
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (196, 'Abrantes', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (197, 'Alcanena', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (198, 'Almeirim', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (199, 'Alpiarça', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (200, 'Benavente', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (201, 'Cartaxo', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (202, 'Chamusca', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (203, 'Constância', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (204, 'Coruche', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (205, 'Entroncamento', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (206, 'Ferreira do Zêzere', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (207, 'Golegã', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (208, 'Mação', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (209, 'Ourém', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (210, 'Rio Maior', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (211, 'Salvaterra de Magos', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (212, 'Santarém', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (213, 'Sardoal', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (214, 'Tomar', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (215, 'Torres Novas', 14);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (216, 'Vila Nova da Barquinha', 14);
--Setúbal
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (217, 'Alcácer do Sal', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (218, 'Alcochete', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (219, 'Almada', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (220, 'Barreiro', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (221, 'Grândola', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (222, 'Moita', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (223, 'Montijo', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (224, 'Palmela', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (225, 'Santiago do Cacém', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (226, 'Seixal', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (227, 'Sesimbra', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (228, 'Setúbal', 15);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (229, 'Sines', 15);
--Viana do Castelo
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (230, 'Arcos de Valdevez', 16);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (231, 'Caminha', 16);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (232, 'Melgaço', 16);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (233, 'Monção', 16);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (234, 'Paredes de Coura', 16);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (235, 'Ponte da Barca', 16);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (236, 'Ponte de Lima', 16);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (237, 'Valença', 16);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (238, 'Viana do Castelo', 16);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (239, 'Vila Nova de Cerveira', 16);
--Vila Real
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (240, 'Alijó', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (241, 'Boticas', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (242, 'Chaves', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (243, 'Mesão Frio', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (244, 'Mondim de Basto', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (245, 'Montalegre', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (246, 'Murça', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (247, 'Peso da Régua', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (248, 'Ribeira de Pena', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (249, 'Sabrosa', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (250, 'Santa Marta de Penaguião', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (251, 'Valpaços', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (252, 'Vila Pouca de Aguiar', 17);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (253, 'Vila Real', 17);
--Viseu
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (254, 'Armamar', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (255, 'Carregal do Sal', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (256, 'Castro Daire', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (257, 'Cinfães', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (258, 'Lamego', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (259, 'Mangualde', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (260, 'Moimenta da Beira', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (261, 'Mortágua', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (262, 'Nelas', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (263, 'Oliveira de Frades', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (264, 'Penalva do Castelo', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (265, 'Penedono', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (266, 'Resende', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (267, 'Santa Comba Dão', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (268, 'São João da Pesqueira', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (269, 'São Pedro do Sul', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (270, 'Sátão', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (271, 'Sernancelhe', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (272, 'Tabuaço', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (273, 'Tarouca', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (274, 'Tondela', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (275, 'Vila Nova de Paiva', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (276, 'Viseu', 18);
INSERT INTO REGION(REGION_ID, REGION_NAME, DISTRICT_ID) VALUES (277, 'Vouzela', 18);

INSERT INTO PROPERTY_KIND(PROPERTY_KIND_ID, PROPERTY_KIND_NAME) VALUES(1000, 'apartment');
INSERT INTO PROPERTY_KIND(PROPERTY_KIND_ID, PROPERTY_KIND_NAME) VALUES(1001, 'village');
INSERT INTO PROPERTY_KIND(PROPERTY_KIND_ID, PROPERTY_KIND_NAME) VALUES(1002, 'terrain');
INSERT INTO PROPERTY_KIND(PROPERTY_KIND_ID, PROPERTY_KIND_NAME) VALUES(1003, 'shop');
INSERT INTO PROPERTY_KIND(PROPERTY_KIND_ID, PROPERTY_KIND_NAME) VALUES(1004, 'office');
INSERT INTO PROPERTY_KIND(PROPERTY_KIND_ID, PROPERTY_KIND_NAME) VALUES(1005, 'garage');
INSERT INTO PROPERTY_KIND(PROPERTY_KIND_ID, PROPERTY_KIND_NAME) VALUES(1006, 'farm');
INSERT INTO PROPERTY_KIND(PROPERTY_KIND_ID, PROPERTY_KIND_NAME) VALUES(1007, 'warehouse');


INSERT INTO PROPERTY(PROPERTY_ID, PROPERTY_NAME, PROPERTY_KIND_ID, PROPERTY_TIPOLOGY,PROPERTY_VILLAGE_TIPOLOGY, PROPERTY_TITLE, PROPERTY_DESCRIPTION, PROPERTY_PRICE, PROPERTY_PRICE_NEGOTIABLE, PROPERTY_POSSIBLE_EXCHANGE, PROPERTY_BUSINESS_TYPE, PROPERTY_STATUS, PROPERTY_USEFULL_AREA, PROPERTY_BRUTE_AREA, PROPERTY_YEAR_OF_CONSTRUCTION, PROPERTY_COUNTRY,  districtId, regionId, PROPERTY_PARISH, PROPERTY_ENERGY_EFFICIENCY, PROPERTY_IS_HIGHLIGHTED) VALUES (1000, 'id_name_1000', 1000, 'T4', NULL,'Fantástico apartamento com  vista para o rio Douro', 'Apartamento localizado no 10º andar com fantásticas vistas sobre o rio Douro, em zona sossegada e com óptimos acessos', 220.000, 't',  't', 'RENTAL', 'USED', 150, 190, 1910, 'portugal', 13, 11, 'ramalde', 'F', 't');
INSERT INTO PROPERTY(PROPERTY_ID, PROPERTY_NAME, PROPERTY_KIND_ID, PROPERTY_TIPOLOGY, PROPERTY_VILLAGE_TIPOLOGY, PROPERTY_TITLE, PROPERTY_DESCRIPTION, PROPERTY_PRICE, PROPERTY_PRICE_NEGOTIABLE, PROPERTY_POSSIBLE_EXCHANGE, PROPERTY_BUSINESS_TYPE, PROPERTY_STATUS, PROPERTY_USEFULL_AREA, PROPERTY_BRUTE_AREA, PROPERTY_YEAR_OF_CONSTRUCTION, PROPERTY_COUNTRY,  districtId, regionId, PROPERTY_PARISH, PROPERTY_ENERGY_EFFICIENCY, PROPERTY_IS_HIGHLIGHTED) VALUES (1001, 'id_name_1001', 1000, 'T2', NULL,'Apartamento com terraço', 'Apartamento com terraço a poente localizado no último andar de prédio de vinte andares.', 120.000, 't',  't', 'RENTAL', 'USED', 150, 190, 1980, 'portugal', 13, 11, 'ramalde', 'F', 't');
INSERT INTO PROPERTY(PROPERTY_ID, PROPERTY_NAME, PROPERTY_KIND_ID, PROPERTY_TIPOLOGY, PROPERTY_VILLAGE_TIPOLOGY, PROPERTY_TITLE, PROPERTY_DESCRIPTION, PROPERTY_PRICE, PROPERTY_PRICE_NEGOTIABLE, PROPERTY_POSSIBLE_EXCHANGE, PROPERTY_BUSINESS_TYPE, PROPERTY_STATUS, PROPERTY_USEFULL_AREA, PROPERTY_BRUTE_AREA, PROPERTY_YEAR_OF_CONSTRUCTION, PROPERTY_COUNTRY,  districtId, regionId, PROPERTY_PARISH, PROPERTY_ENERGY_EFFICIENCY, PROPERTY_IS_HIGHLIGHTED) VALUES (1002, 'id_name_1002', 1000, NULL, 'V5', 'Pequena quinta para turismo rural', 'Vendo pequena quinta no Douro para restauro com óptima vocação para turismo rural.', 1200000.000, 't',  't', 'SALE', 'USED', 150, 190, 2009, 'portugal', 13, 11, 'ramalde', 'F', 'f');
INSERT INTO PROPERTY(PROPERTY_ID, PROPERTY_NAME, PROPERTY_KIND_ID, PROPERTY_TIPOLOGY, PROPERTY_VILLAGE_TIPOLOGY, PROPERTY_TITLE, PROPERTY_DESCRIPTION, PROPERTY_PRICE, PROPERTY_PRICE_NEGOTIABLE, PROPERTY_POSSIBLE_EXCHANGE, PROPERTY_BUSINESS_TYPE, PROPERTY_STATUS, PROPERTY_USEFULL_AREA, PROPERTY_BRUTE_AREA, PROPERTY_YEAR_OF_CONSTRUCTION, PROPERTY_COUNTRY,  districtId, regionId, PROPERTY_PARISH, PROPERTY_ENERGY_EFFICIENCY, PROPERTY_IS_HIGHLIGHTED) VALUES (1003, 'id_name_1003', 1006, NULL, 'V4', 'Pequena quinta de turismo rural', 'Vendo pequena quinta no Alto Minho para restauro.', 80000.000, 't',  't', 'SALE', 'USED', 150, 190, 1710, 'portugal', 13, 16, 'ramalde', 'F', 't');

INSERT INTO PROPERTY(PROPERTY_ID, PROPERTY_NAME, PROPERTY_KIND_ID, PROPERTY_TIPOLOGY,PROPERTY_VILLAGE_TIPOLOGY, PROPERTY_TITLE, PROPERTY_DESCRIPTION, PROPERTY_PRICE, PROPERTY_PRICE_NEGOTIABLE, PROPERTY_POSSIBLE_EXCHANGE, PROPERTY_BUSINESS_TYPE, PROPERTY_STATUS, PROPERTY_USEFULL_AREA, PROPERTY_BRUTE_AREA, PROPERTY_YEAR_OF_CONSTRUCTION, PROPERTY_COUNTRY,  districtId, regionId, PROPERTY_PARISH, PROPERTY_ENERGY_EFFICIENCY, PROPERTY_IS_HIGHLIGHTED) VALUES (1006, 'id_name_1006', 1000, 'T1_PLUS_1', NULL,'Fantástico apartamento com  varanda no 10º.', 'Óptimos acessos, junto a escolas. Andar com fantásticas vistas sobre o rio Douro, em zona sossegada e com óptimos acessos', 95000.000, 't',  't', 'SALE', 'NEW', 85, 90, 2010, 'portugal', 13, 11, 'ramalde', 'F', 't');
INSERT INTO PROPERTY(PROPERTY_ID, PROPERTY_NAME, PROPERTY_KIND_ID, PROPERTY_TIPOLOGY,PROPERTY_VILLAGE_TIPOLOGY, PROPERTY_TITLE, PROPERTY_DESCRIPTION, PROPERTY_PRICE, PROPERTY_PRICE_NEGOTIABLE, PROPERTY_POSSIBLE_EXCHANGE, PROPERTY_BUSINESS_TYPE, PROPERTY_STATUS, PROPERTY_USEFULL_AREA, PROPERTY_BRUTE_AREA, PROPERTY_YEAR_OF_CONSTRUCTION, PROPERTY_COUNTRY,  districtId, regionId, PROPERTY_PARISH, PROPERTY_ENERGY_EFFICIENCY, PROPERTY_IS_HIGHLIGHTED) VALUES (1007, 'id_name_1007', 1000, 'T2', NULL,'Apartamento na baixa', 'Apartamento localizado no 5º com fantásticas vistas sobre a cidade com óptimos acessos', 600.000, 't',  't', 'RENTAL', 'USED', 150, 190, 1910, 'portugal', 13, 11, 'ramalde', 'F', 't');
INSERT INTO PROPERTY(PROPERTY_ID, PROPERTY_NAME, PROPERTY_KIND_ID, PROPERTY_TIPOLOGY,PROPERTY_VILLAGE_TIPOLOGY, PROPERTY_TITLE, PROPERTY_DESCRIPTION, PROPERTY_PRICE, PROPERTY_PRICE_NEGOTIABLE, PROPERTY_POSSIBLE_EXCHANGE, PROPERTY_BUSINESS_TYPE, PROPERTY_STATUS, PROPERTY_USEFULL_AREA, PROPERTY_BRUTE_AREA, PROPERTY_YEAR_OF_CONSTRUCTION, PROPERTY_COUNTRY,  districtId, regionId, PROPERTY_PARISH, PROPERTY_ENERGY_EFFICIENCY, PROPERTY_IS_HIGHLIGHTED) VALUES (1008, 'id_name_1008', 1006, 'T4', NULL,'Quinta para resturar', 'Óptima quinta para viver', 1350000.000, 't',  't', 'SALE', 'USED', 150, 190, 1810, 'portugal', 13, 11, 'ramalde', 'F', 't');
INSERT INTO PROPERTY(PROPERTY_ID, PROPERTY_NAME, PROPERTY_KIND_ID, PROPERTY_TIPOLOGY,PROPERTY_VILLAGE_TIPOLOGY, PROPERTY_TITLE, PROPERTY_DESCRIPTION, PROPERTY_PRICE, PROPERTY_PRICE_NEGOTIABLE, PROPERTY_POSSIBLE_EXCHANGE, PROPERTY_BUSINESS_TYPE, PROPERTY_STATUS, PROPERTY_USEFULL_AREA, PROPERTY_BRUTE_AREA, PROPERTY_YEAR_OF_CONSTRUCTION, PROPERTY_COUNTRY,  districtId, regionId, PROPERTY_PARISH, PROPERTY_ENERGY_EFFICIENCY, PROPERTY_IS_HIGHLIGHTED) VALUES (1009, 'id_name_1009', 1004, 'T4', NULL,'Escritório no centro do Porto', 'Óptimos acessos e estacionamento privativo.', 400.000, 't',  't', 'RENTAL', 'USED', 25, 35, 1990, 'portugal', 13, 11, 'ramalde', 'F', 't');
INSERT INTO PROPERTY(PROPERTY_ID, PROPERTY_NAME, PROPERTY_KIND_ID, PROPERTY_TIPOLOGY,PROPERTY_VILLAGE_TIPOLOGY, PROPERTY_TITLE, PROPERTY_DESCRIPTION, PROPERTY_PRICE, PROPERTY_PRICE_NEGOTIABLE, PROPERTY_POSSIBLE_EXCHANGE, PROPERTY_BUSINESS_TYPE, PROPERTY_STATUS, PROPERTY_USEFULL_AREA, PROPERTY_BRUTE_AREA, PROPERTY_YEAR_OF_CONSTRUCTION, PROPERTY_COUNTRY,  districtId, regionId, PROPERTY_PARISH, PROPERTY_ENERGY_EFFICIENCY, PROPERTY_IS_HIGHLIGHTED) VALUES (1010, 'id_name_1010', 1000, 'T4', NULL,'Apartamento em último andar restaurado', 'Apartamento localizado no 10º andar com fantásticas vistas sobre o rio Douro, em zona sossegada e com óptimos acessos', 1220.000, 't',  't', 'RENTAL', 'USED', 250, 290, 2013, 'portugal', 13, 11, 'ramalde', 'F', 't');

INSERT INTO CLOUDINARY_IMAGE(CLOUDINARY_IMAGE_ID, CLOUDINARY_HIGHLIGHT_IMAGE_URL, CLOUDINARY_DETAIL_MAIN_IMAGE_URL, PROPERTY_ID_FK) VALUES(1000, 'http://res.cloudinary.com/homerenting/image/upload/v1398720688/03_zcl3ov.jpg', 'http://res.cloudinary.com/homerenting/image/upload/v1398720688/03_zcl3ov.jpg',1000);
INSERT INTO CLOUDINARY_IMAGE(CLOUDINARY_IMAGE_ID, CLOUDINARY_HIGHLIGHT_IMAGE_URL, CLOUDINARY_DETAIL_MAIN_IMAGE_URL, PROPERTY_ID_FK) VALUES(1001, 'http://res.cloudinary.com/homerenting/image/upload/v1398720685/07_kjziex.jpg', 'http://res.cloudinary.com/homerenting/image/upload/v1398720685/07_kjziex.jpg', 1001);
INSERT INTO CLOUDINARY_IMAGE(CLOUDINARY_IMAGE_ID, CLOUDINARY_HIGHLIGHT_IMAGE_URL, CLOUDINARY_DETAIL_MAIN_IMAGE_URL, PROPERTY_ID_FK) VALUES(1002, 'http://res.cloudinary.com/homerenting/image/upload/v1398720688/06_kfopah.jpg', 'http://res.cloudinary.com/homerenting/image/upload/v1398720688/06_kfopah.jpg', 1002);
INSERT INTO CLOUDINARY_IMAGE(CLOUDINARY_IMAGE_ID, CLOUDINARY_HIGHLIGHT_IMAGE_URL, CLOUDINARY_DETAIL_MAIN_IMAGE_URL, PROPERTY_ID_FK) VALUES(1003, 'http://res.cloudinary.com/homerenting/image/upload/v1398720690/04_z633pb.jpg', 'http://res.cloudinary.com/homerenting/image/upload/v1398720690/04_z633pb.jpg', 1003);




INSERT INTO COMPANY_MOTD(COMPANY_MOTD_ID, COMPANY_MOTD_MOTD) VALUES (1, 'tretas motd');


INSERT INTO ACCOUNT_TOKENS(id, ACCOUNT_TOKENS_TOKEN) VALUES(1000000, '8017ae75-d285-44f3-b618-fd008b1de518');
INSERT INTO USER_SHORT_PROFILE(USER_SHORT_PROFILE_ID, USER_SHORT_PROFILE_EMAIL, USER_PASSWORD, isAccountEnabled, ACCOUNT_TOKEN_ID) VALUES (1000000, 'arthur.m@iol.pt', '123456', 'f', 1000000);
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES(1000000, 'ROLE_USER');
INSERT INTO ROLE(ROLE_ID, ROLE_NAME) VALUES(1000001, 'ROLE_ADMIN');
INSERT INTO USER_SHORT_PROFILE_ROLE(USER_SHORT_PROFILE_ID, ROLE_ID) VALUES (1000000, 1000000);
INSERT INTO USER_SHORT_PROFILE_ROLE(USER_SHORT_PROFILE_ID, ROLE_ID) VALUES (1000000, 1000001);

INSERT INTO APARTMENT(APARTMENT_ID, APARTMENT_DESCRIPTION) VALUES (1000000, 'Brutal');
INSERT INTO APARTMENT(APARTMENT_ID, APARTMENT_DESCRIPTION) VALUES (1000001, 'Rasca');
INSERT INTO APARTMENT(APARTMENT_ID, APARTMENT_DESCRIPTION) VALUES (1000002, 'Pequeno');

--INSERT INTO USERS (id, firstName, lastName, email, address, zipcode, city, country, userKind, company, nif, phoneNumber, cellPhone, fax, password) values (0, 'arthur', 'portas', 'arthurportas@gmail.com', 'rua a voz dos ridiculos, 40, 1� h2', '4250551', 'porto', 'portugal', 'particular', '', '221446834', '220109606', '935705832', '', 'tretas')

--PARISH is equivalent to FREGUESIA
--PORTO-PORTO
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (1, 'Nevogilde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (2, 'Aldoar', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (3, 'Foz do douro', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (4, 'Ramalde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (5, 'Massarelos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (6, 'Cedofeita', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (7, 'Miragaia', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (8, 'Lordelo do Ouro', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (9, 'Paranhos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (10, 'Santo Ildefonso', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (11, 'Vitória', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (12, 'São Nicolau', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (13, 'Sé', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (14, 'Bonfim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (15, 'Campanhã', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (16, 'União das freguesias de Aldoar, Foz do Douro e Nevogilde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (17, 'União das freguesias de Cedofeita, Santo Ildefonso, Sé, Miragaia, são Nicolau e Vitória', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (18, 'União das freguesias de Lordelo do Ouro e Massarelos', 11);
--PORTO-AMARANTE
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (19, 'Aboadela', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (20, 'Aboim', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (21, 'Amarante(São Gonçalo)', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (22, 'Ansiães', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (23, 'Ataíde', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (24, 'Bustelo', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (25, 'Canadelo', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (26, 'Candemil', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (27, 'Carneiro', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (28, 'Carvalho de Rei', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (29, 'Cepelos', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (30, 'Chapa', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (31, 'Figueiró(Santa Cristina)', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (32, 'Figueiró(Santiago)', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (33, 'Freguim', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (34, 'Freixo de Baixo', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (35, 'Freixo de Cima', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (36, 'Fridão', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (37, 'Gatão', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (38, 'Gondar', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (39, 'Gouveia(São Simão)', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (40, 'Jazente', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (41, 'Lomba', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (42, 'Louredo', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (43, 'Lufrei', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (44, 'Madalena', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (45, 'Mancelos', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (46, 'Oliveira', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (47, 'Olo', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (48, 'Padronelo', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (49, 'Real', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (50, 'Rebordelo', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (51, 'Salvador do Monte', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (52, 'Sanche', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (53, 'Telões', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (54, 'Travanca', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (55, 'União das freguesias de Aboadela, Sanche e Várzea', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (56, 'União das freguesias de Amarante(São Gonçalo), Madalena, Cepelos e Gatão', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (57, 'União das freguesias de Bustelo, Carneiro e Carvalho de Rei', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (58, 'União das freguesias de Figueiró(Santiago e Santa Cristina)', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (59, 'União das freguesias de Freixo de Cima e de Baixo', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (60, 'União das freguesias de Olo e Canadelo', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (61, 'União das freguesias de Real, Ataíde e Oliveira', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (62, 'União das freguesias de Vila Garcia, Aboim e Chapa', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (63, 'Várzea', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (64, 'Vila Caiz', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (65, 'Vila Chã do Marão', 1);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (66, 'Vila Garcia', 1);
--PORTO-BAIÃO
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (67, 'Ancede', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (68, 'Baião(Santa Leocádia)', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (69, 'Campelo', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (70, 'Frende', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (71, 'Gestaçô', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (72, 'Gove', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (73, 'Grilo', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (74, 'Loivos da Ribeira', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (75, 'Loivos do Monte', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (76, 'Mesquinhata', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (77, 'Ovil', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (78, 'Ribadouro', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (79, 'Santa cruz do Douro', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (80, 'Santa Marinha do Zêzere', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (81, 'São Tomé de Covelas', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (82, 'Teixeira', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (83, 'Teixeiró', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (84, 'Tresouras', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (85, 'União das freguesias de Ancede e Ribadouro', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (86, 'União das freguesias de Baião(Santa Leocádia) e Mesquinhata', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (87, 'União das freguesias de Campelo e Ovil', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (88, 'União das freguesias de Loivos da Ribeira e Tresouras', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (89, 'União das freguesias de Santa Cruz do Douro e São Tomé de Covelas', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (90, 'União das freguesias de Teixeira e Teixeiró', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (91, 'Valadares', 2);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (92, 'Vilariz', 2);
--PORTO-FELGUEIRAS
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (93, 'Aião', 11);--TODO correct regiond id from here
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (94, 'Airães', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (95, 'Borba de Godim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (96, 'Caramos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (97, 'Friande', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (98, 'Idães', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (99, 'Jugueiros', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (100, 'Lagares', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (101, 'Lordelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (102, 'Macieira da Lixa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (103, 'Margaride (Santa Eulália)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (104, 'Moure', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (105, 'Pedreira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (106, 'Penacova', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (107, 'Pinheiro', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (108, 'Pombeiro de Ribavizela', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (109, 'Rande', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (110, 'Refontoura', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (111, 'Regilde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (112, 'Revinhade', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (113, 'Santão', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (114, 'Sendim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (115, 'Sernande', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (116, 'Sousa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (117, 'Torrados', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (118, 'Unhão', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (119, 'União das freguesias de Macieira da Lixa e Caramos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (120, 'União das freguesias de Macieira da Lixa e Caramos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (121, 'União das freguesias de Margaride (Santa Eulália), Várzea, Lagares, Varziela e Moure', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (122, 'União das freguesias de Pedreira, Rande e Sernande', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (123, 'União das freguesias de Torrados e Sousa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (124, 'União das freguesias de Unhão e Lordelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (125, 'União das freguesias de Vila Cova da Lixa e Borba de Godim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (126, 'União das freguesias de Vila Fria e Vizela (São Jorge)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (127, 'União das freguesias de Vila Verde e Santão', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (128, 'Várzea', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (129, 'Varziela', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (130, 'Vila Cova da Lixa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (131, 'Vila Fria', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (132, 'Vila Verde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (133, 'Vizela (São Jorge)', 11);
--PORTO-GONDOMAR
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (134, 'Baguim do Monte (Rio Tinto)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (135, 'Covelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (136, 'Fânzeres', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (137, 'Foz do Sousa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (138, 'Gondomar (São Cosme)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (139, 'Jovim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (140, 'Lomba', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (141, 'Medas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (142, 'Melres', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (143, 'Rio Tinto', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (144, 'São Pedro da Cova', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (145, 'União das freguesias de Fânzeres e São Pedro da Cova', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (146, 'União das freguesias de Foz do Sousa e Covelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (147, 'União das freguesias de Gondomar (São Cosme), Valbom e Jovim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (148, 'União das freguesias de Melres e Medas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (149, 'Valbom', 11);
--PORTO_LOUSADA
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (150, 'Alvarenga', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (151, 'Aveleda', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (152, 'Barrosas (Santo Estevão)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (153, 'Boim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (154, 'Caíde de Rei', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (155, 'Casais', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (156, 'Cernadelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (157, 'Covas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (158, 'Cristelos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (159, 'Figueiras', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (160, 'Lodares', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (161, 'Lousada (Santa Margarida)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (162, 'Lousada (São Miguel)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (163, 'Lustosa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (164, 'Macieira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (165, 'Meinedo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (166, 'Nespereira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (167, 'Nevogilde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (168, 'Nogueira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (169, 'Ordem', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (170, 'Pias', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (171, 'Silvares', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (172, 'Sousela', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (173, 'Torno', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (174, 'União das freguesias de Cernadelo e Lousada (São Miguel e Santa Margarida)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (175, 'União das freguesias de Cristelos, Boim e Ordem', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (176, 'União das freguesias de Figueiras e Covas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (177, 'União das freguesias de Lustosa e Barrosas (Santo Estêvão)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (178, 'União das freguesias de Nespereira e Casais', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (179, 'União das freguesias de Silvares, Pias, Nogueira e Alvarenga', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (180, 'Vilar do Torno e Alentém', 11);
--PORTO-MAIA
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (181, 'Águas Santas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (182, 'Avioso (Santa Maria)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (183, 'Avioso (São Pedro)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (184, 'Barca', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (185, 'Castêlo da Maia', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (186, 'Cidade da Maia', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (187, 'Folgosa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (188, 'Gemunde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (189, 'Gondim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (190, 'Gueifães', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (191, 'Maia', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (192, 'Milheirós', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (193, 'Moreira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (194, 'Nogueira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (195, 'Nogueira e Silva Escura', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (196, 'Pedrouços', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (197, 'São Pedro Fins', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (198, 'Silva Escura', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (199, 'Vermoim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (200, 'Vila Nova da Telha', 11);
--PORTO-MARCO CANAVEZES
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (201, 'Alpendorada, Várzea e Torrão', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (202, 'Alpendurada e Matos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (203, 'Ariz', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (204, 'Avessadas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (205, 'Avessadas e Rosém', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (206, 'Banho e Carvalhosa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (207, 'Bem Viver', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (208, 'Constance', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (209, 'Favões', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (210, 'Folhada', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (211, 'Fornos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (212, 'Freixo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (213, 'Livração', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (214, 'Magrelos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (215, 'Manhuncelos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (216, 'Marco', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (217, 'Maureles', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (218, 'Paços de Gaiolo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (219, 'Paredes de Viadores', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (220, 'Paredes de Viadores e Manhuncelos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (221, 'Penha Longa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (222, 'Penhalonga e Paços de Gaiolo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (223, 'Rio de Galinhas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (224, 'Rosém', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (225, 'Sande', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (226, 'Sande e São Lourenço', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (227, 'Santo Isidoro', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (228, 'São Lourenço do Douro', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (229, 'São Nicolau', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (230, 'Soalhães', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (231, 'Sobretâmega', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (232, 'Tabuado', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (233, 'Torrao', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (234, 'Toutosa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (235, 'Tuias', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (236, 'Várzea da Ovelha e Aliviada', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (237, 'Várzea do Douro', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (238, 'Várzea, Aliviada e Folhada', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (239, 'Vila Boa de Quires', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (240, 'Vila Boa de Quires e Maureles', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (241, 'Vila Boa do Bispo', 11);
--PORTO-MATOSINHOS
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (242, 'Custoias', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (243, 'Guifões', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (244, 'Lavra', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (245, 'Leca da Palmeira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (246, 'Leça do Balio', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (247, 'Matosinhos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (248, 'Perafita', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (249, 'Santa Cruz do Bispo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (250, 'São Mamede de Infesta', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (251, 'Senhora da Hora', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (252, 'União das freguesias de Custóias, Leça do Balio e Guifões', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (253, 'União das freguesias de Matosinhos e Leça da Palmeira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (254, 'União das freguesias de Perafita, Lavra e Santa Cruz do Bispo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (255, 'União das freguesias de São Mamede de Infesta e Senhora da Hora', 11);
--PORTO-PAÇOS FERREIRA
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (256, 'Arreigada', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (257, 'Carvalhosa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (258, 'Codessos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (259, 'Eiriz', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (260, 'Ferreira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (261, 'Figueiró', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (262, 'Frazão', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (263, 'Frazão Arreigada', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (264, 'Freamunde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (265, 'Lamoso', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (266, 'Meixomil', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (267, 'Modelos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (268, 'Paços de Ferreira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (269, 'Paços de Ferreira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (270, 'Penamaior', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (271, 'Raimonda', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (272, 'Sanfins de Ferreira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (273, 'Sanfins Lamoso Codessos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (274, 'Seroa', 11);
--PORTO-PAREDES
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (275, 'Aguiar de Sousa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (276, 'Astromil', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (277, 'Baltar', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (278, 'Beire', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (279, 'Besteiros', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (280, 'Bitarães', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (281, 'Castelões de Cêpeda', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (282, 'Cete', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (283, 'Cristelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (284, 'Duas Igrejas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (285, 'Gandra', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (286, 'Gondalães', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (287, 'Lordelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (288, 'Louredo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (289, 'Madalena', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (290, 'Mouriz', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (291, 'Parada de Todeia', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (292, 'Paredes', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (293, 'Rebordosa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (294, 'Recarei', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (295, 'Sobreira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (296, 'Sobrosa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (297, 'Vandoma', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (298, 'Vila Cova de Carros', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (299, 'Vilela', 11);
--PORTO-PENAFIEL
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (300, 'Abragão', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (301, 'Boelhe', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (302, 'Bustelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (303, 'Cabeça Santa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (304, 'Canelas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (305, 'Capela', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (306, 'Castelões', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (307, 'Croca', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (308, 'Duas Igrejas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (309, 'Eja', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (310, 'Figueira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (311, 'Fonte Arcada', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (312, 'Galegos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (313, 'Guilhufe', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (314, 'Guilhufe e Urrô', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (315, 'Irivo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (316, 'Lagares', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (317, 'Lagares e Figueira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (318, 'Luzim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (319, 'Luzim e Vila Cova', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (320, 'Marecos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (321, 'Milhundos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (322, 'Novelas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (323, 'Oldrões', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (324, 'Paço de Sousa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (325, 'Paredes', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (326, 'Penafiel', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (327, 'Perozelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (328, 'Pinheiro', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (329, 'Portela', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (330, 'Rans', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (331, 'Recezinhos (São Mamede)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (332, 'Recezinhos (São Martinho)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (333, 'Rio de Moinhos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (334, 'Rio Mau', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (335, 'Santa Marta', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (336, 'Santiago de Subarrifana', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (337, 'Sebolido', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (338, 'Termas de São Vicente', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (339, 'Urrô', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (340, 'Valpedre', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (341, 'Vila Cova', 11);
--PORTO-PÓVOA VARZIM
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (342, 'Aguçadoura', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (343, 'Amorim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (344, 'Argivai', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (345, 'Aver-o-Mar', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (346, 'Balazar', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (347, 'Beiriz', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (348, 'Estela', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (349, 'Laundos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (350, 'Navais', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (351, 'Póvoa de Varzim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (352, 'Rates', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (353, 'Terroso', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (354, 'União das freguesias da Póvoa de Varzim, Beiriz e Argivai', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (355, 'União das freguesias de Aguçadoura e Navais', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (356, 'União das freguesias de Aver-o-Mar, Amorim e Terroso', 11);
--PORTO-SANTO TIRSO
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (357, 'Agrela', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (358, 'Água Longa', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (359, 'Areias', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (360, 'Aves', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (361, 'Burgães', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (362, 'Campo (São Martinho)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (363, 'Carreira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (364, 'Couto (Santa Cristina)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (365, 'Couto (São Miguel)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (366, 'Guimarei', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (367, 'Lama', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (368, 'Lamelas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (369, 'Monte Córdova', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (370, 'Negrelos (São Mamede)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (371, 'Negrelos (São Tomé)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (372, 'Palmeira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (373, 'Rebordões', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (374, 'Refojos de Riba de Ave', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (375, 'Reguenga', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (376, 'Roriz', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (377, 'Santo Tirso<', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (378, 'São Salvador do Campo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (379, 'Sequeiró', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (380, 'União das freguesias de Areias, Sequeiró, Lama e Palmeira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (381, 'União das freguesias de Campo (São Martinho), São Salvador do Campo e Negrelos (São Mamede)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (382, 'União das freguesias de Carreira e Refojos de Riba de Ave', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (383, 'União das freguesias de Lamelas e Guimarei', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (384, 'União das freguesias de Santo Tirso, Couto (Santa Cristina e São Miguel) e Burgães', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (385, 'Vilarinho', 11);
--PORTO-TROFA
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (386, 'Alvarelhos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (387, 'Bougado (Santiago)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (388, 'Coronado (São Mamede)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (389, 'Coronado (São Romão)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (390, 'Covelas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (391, 'Guidões', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (392, 'Muro', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (393, 'São Martinho de Bougado', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (394, 'União das freguesias de Alvarelhos e Guidões', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (395, 'União das freguesias de Bougado (São Martinho e Santiago)', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (396, 'União das freguesias de Coronado (São Romão e São Mamede)', 11);
--PORTO-VALONGO
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (397, 'Alfena', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (398, 'Campo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (399, 'Ermesinde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (400, 'Sobrado', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (401, 'União das freguesias de Campo e Sobrado', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (402, 'Valongo', 11);
--PORTO-VILA CONDE
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (403, 'Arcos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (404, 'Árvore', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (405, 'Aveleda', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (406, 'Azurara', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (407, 'Bagunte', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (408, 'Canidelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (409, 'Fajozes', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (410, 'Ferreiró', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (411, 'Fornelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (412, 'Gião', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (413, 'Guilhabreu', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (414, 'Junqueira', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (415, 'Labruge', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (416, 'Macieira da Maia', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (417, 'Malta', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (418, 'Mindelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (419, 'Modivas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (420, 'Mosteiró', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (421, 'Outeiro', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (422, 'Maior', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (423, 'Parada', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (424, 'Retorta', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (425, 'Rio Mau', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (426, 'Tougues', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (427, 'Touguinha', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (428, 'Touguinhó', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (429, 'União das freguesias de Bagunte, Ferreiró, Outeiro Maior e Parada', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (430, 'União das freguesias de Fornelo e Vairão', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (431, 'União das freguesias de Malta e Canidelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (432, 'União das freguesias de Retorta e Tougues', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (433, 'União das freguesias de Rio Mau e Arcos', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (434, 'União das freguesias de Touguinha e Touguinhó', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (435, 'União das freguesias de Vilar e Mosteiró', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (436, 'Vairão', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (437, 'Vila Chã', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (438, 'Vila do Conde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (439, 'Vilar', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (440, 'Vilar de Pinheiro', 11);
--PORTO-VILA NOVA GAIA
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (441, 'Arcozelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (442, 'Avintes', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (443, 'Canelas', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (444, 'Canidelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (445, 'Crestuma', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (446, 'Grijó', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (447, 'Gulpilhares', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (448, 'Lever', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (449, 'Madalena', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (450, 'Mafamude', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (451, 'Olival', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (452, 'Oliveira do Douro', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (453, 'Pedroso', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (454, 'Perozinho', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (455, 'Sandim', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (456, 'Santa Marinha', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (457, 'São Félix da Marinha', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (458, 'São Pedro da Afurada', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (459, 'Seixezelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (460, 'Sermonde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (461, 'Serzedo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (462, 'União das freguesias de Grijó e Sermonde', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (463, 'União das freguesias de Gulpilhares e Valadares', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (464, 'União das freguesias de Mafamude e Vilar do Paraíso', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (465, 'União das freguesias de Pedroso e Seixezelo', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (466, 'União das freguesias de Sandim, Olival, Lever e Crestuma', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (467, 'União das freguesias de Santa Marinha e São Pedro da Afurada', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (468, 'União das freguesias de Serzedo e Perosinho', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (469, 'Valadares', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (470, 'Vilar de Andorinho', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (471, 'Vilar do Paraíso', 11);

INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (472, '', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (473, '', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (474, '', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (475, '', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (476, '', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (477, '', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (478, '', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (479, '', 11);
INSERT INTO PARISH(PARISH_ID, PARISH_NAME, REGION_ID) VALUES (480, '', 11);

/*
AVEIRO-AGUÉDA
<option value="freguesia.php?cod=010101">Agadão</option>
                                                                                <option value="freguesia.php?cod=010102">Aguada de Baixo</option>
                                                                                <option value="freguesia.php?cod=010103">Aguada de Cima</option>
                                                                                <option value="freguesia.php?cod=010104">Águeda</option>
                                                                                <option value="freguesia.php?cod=010105">Barrô</option>
                                                                                <option value="freguesia.php?cod=010106">Belazaima do Chão</option>
                                                                                <option value="freguesia.php?cod=010120">Borralha</option>
                                                                                <option value="freguesia.php?cod=010107">Castanheira do Vouga</option>
                                                                                <option value="freguesia.php?cod=010108">Espinhel</option>
                                                                                <option value="freguesia.php?cod=010109">Fermentelos</option>
                                                                                <option value="freguesia.php?cod=010110">Lamas do Vouga</option>
                                                                                <option value="freguesia.php?cod=010111">Macieira de Alcoba</option>
                                                                                <option value="freguesia.php?cod=010112">Macinhata do Vouga</option>
                                                                                <option value="freguesia.php?cod=010113">Óis da Ribeira</option>
                                                                                <option value="freguesia.php?cod=010114">Préstimo</option>
                                                                                <option value="freguesia.php?cod=010115">Recardães</option>
                                                                                <option value="freguesia.php?cod=010116">Segadães</option>
                                                                                <option value="freguesia.php?cod=010117">Travassô</option>
                                                                                <option value="freguesia.php?cod=010118">Trofa</option>
                                                                                <option value="freguesia.php?cod=010121">União das freguesias de Águeda e Borralha</option>
                                                                                <option value="freguesia.php?cod=010122">União das freguesias de Barrô e Aguada de Baixo</option>
                                                                                <option value="freguesia.php?cod=010123">União das freguesias de Belazaima do Chão, Castanheira do Vouga e Agadão</option>
                                                                                <option value="freguesia.php?cod=010124">União das freguesias de Recardães e Espinhel</option>
                                                                                <option value="freguesia.php?cod=010125">União das freguesias de Travassô e Óis da Ribeira</option>
                                                                                <option value="freguesia.php?cod=010126">União das freguesias de Trofa, Segadães e Lamas do Vouga</option>
                                                                                <option value="freguesia.php?cod=010127">União das freguesias do Préstimo e Macieira de Alcoba</option>
                                                                                <option value="freguesia.php?cod=010119">Valongo do Vouga</option>

AVEIRO-ÁGUEDA-
*/